CREATE TABLE STAGE.BASE_SHIP_DATA (
IMO_NUMBER VARCHAR(100),
PROPRIETARY_NUMBER VARCHAR(100),
SOURCE_SYSTEM VARCHAR(100),
FLAG VARCHAR(100),
MAIN_NAME VARCHAR(255),
SECONDARY_NAME VARCHAR(255),
HOME_PORT VARCHAR(255),
CALL_SIGN VARCHAR(50),
EXTENDED_URL VARCHAR(255),
DATETIME VARCHAR(50)
);

