###############################################################################
#
#   Fleet Scraper configuration file.
#
#   Created:  Dmitrii Gusev, 09.12.2021
#   Modified:
#
###############################################################################
