DELIMITER //
CREATE PROCEDURE DV.LOAD_T_SHIP_HS_BASE_SHIP_DATA ()
BEGIN
	
	INSERT INTO DV.T_SHIP_HS (SHIP_ID, VALID_FROM, FLAG, MAIN_NAME, SECONDARY_NAME, HOME_PORT, CALL_SIGN, ROW_HASH, LOAD_DTTM)
	SELECT H.SHIP_ID, STR_TO_DATE(STG.DATETIME, '%d-%b-%Y %T') AS VALID_FROM, STG.FLAG, STG.MAIN_NAME, 
		STG.SECONDARY_NAME, STG.HOME_PORT, STG.CALL_SIGN, MD5(CONCAT_WS('#', STG.FLAG, STG.MAIN_NAME, STG.SECONDARY_NAME, STG.HOME_PORT, STG.CALL_SIGN)) AS ROW_HASH, SYSDATE()
	FROM STAGE.BASE_SHIP_DATA STG
		JOIN DV.T_SHIP_H H
			ON (STG.IMO_NUMBER = H.IMO_NUM OR (STG.IMO_NUMBER IS NULL AND H.IMO_NUM IS NULL))
				AND (STG.PROPRIETARY_NUMBER = H.REG_NUM OR (STG.PROPRIETARY_NUMBER IS NULL AND H.REG_NUM IS NULL))
                AND STG.SOURCE_SYSTEM = H.SRC_NM
		LEFT JOIN DV.T_SHIP_HS TGT
			ON H.SHIP_ID = TGT.SHIP_ID
				AND TGT.VALID_TO IS NULL
				AND TGT.ROW_HASH = MD5(CONCAT_WS('#', STG.FLAG, STG.MAIN_NAME, STG.SECONDARY_NAME, STG.HOME_PORT, STG.CALL_SIGN))
	WHERE TGT.SHIP_ID IS NULL;
        
	UPDATE DV.T_SHIP_HS AS TGT,
		(
			SELECT SHIP_ID, VALID_FROM, VALID_TO_NEW
			FROM (
				SELECT SHIP_ID, VALID_FROM, VALID_TO, MAX(VALID_FROM) OVER (PARTITION BY SHIP_ID ORDER BY VALID_FROM ASC ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING) AS VALID_TO_NEW
				FROM DV.T_SHIP_HS
			) X
			WHERE VALID_TO_NEW IS NOT NULL AND (VALID_TO <> VALID_TO_NEW OR VALID_TO IS NULL)
		) AS SRC
	SET TGT.VALID_TO = SRC.VALID_TO_NEW
    WHERE TGT.SHIP_ID = SRC.SHIP_ID
		AND TGT.VALID_FROM = SRC.VALID_FROM;
END;
//
