DELIMITER //
CREATE PROCEDURE DV.LOAD_T_SHIP_H_BASE_SHIP_DATA ()
BEGIN
	DECLARE MAX_ID INTEGER;

	SELECT COALESCE(MAX(SHIP_ID),0)
    INTO MAX_ID
    FROM DV.T_SHIP_H;

	INSERT INTO DV.T_SHIP_H (SHIP_ID, IMO_NUM, REG_NUM, SRC_NM, LOAD_DTTM)
		SELECT MAX_ID + ROW_NUMBER() OVER (), IMO_NUMBER, PROPRIETARY_NUMBER, SOURCE_SYSTEM, SYSDATE()
		FROM STAGE.BASE_SHIP_DATA STG
			LEFT JOIN DV.T_SHIP_H TGT
				ON (STG.IMO_NUMBER = TGT.IMO_NUM OR (STG.IMO_NUMBER IS NULL AND TGT.IMO_NUM IS NULL))
					AND (STG.PROPRIETARY_NUMBER = TGT.REG_NUM OR (STG.PROPRIETARY_NUMBER IS NULL AND TGT.REG_NUM IS NULL))
                    AND STG.SOURCE_SYSTEM = TGT.SRC_NM 
		WHERE TGT.SHIP_ID IS NULL
		GROUP BY IMO_NUMBER, PROPRIETARY_NUMBER, SOURCE_SYSTEM;
END;
//